version: "3.2"
services:
  docker-registry:
    image: registry:2
    container_name: "docker-registry"
    ports:
      - "5000:5000"
    volumes:
      - /docker-registry/registry:/var/lib/registry
        
  docker-registry-ui:
    image: "koradkleine/docker-registry-frontend:v2"
    container_name: "docker-registry-ui"
    ports:
      - "8000:80"
    environment:
      ENV_DOCKER_REGISTRY_HOST: docker-registry
      ENV_DOCKER_REGISTRY_PORT: 5000
