version: '3.7'
services:
  nginx:
    image: nginx:alpine
    container_name: alpine-nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./:/var/www
      - ./config/nginx:/etc/nginx/conf.d/