version: "3.8"

services:
  label-studio:
    image: heartexlabs/label-studio:latest
    container_name: label_studio
    ports:
      - "8080:8080"
    environment:
      - DJANGO_DB=default
      - POSTGRE_NAME=labelstudio
      - POSTGRE_USER=labelstudio
      - POSTGRE_PASSWORD=yourpassword
      - POSTGRE_HOST=db
      - POSTGRE_PORT=5432
      - LABEL_STUDIO_LOCAL_FILES_SERVING_ENABLED=true
      - LABEL_STUDIO_LOCAL_FILES_DOCUMENT_ROOT=/data
    volumes:
      - ./data:/label-studio/data
    restart: unless-stopped
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=labelstudio
      - POSTGRES_USER=labelstudio
      - POSTGRES_PASSWORD=yourpassword
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: