version: '3.7'
#https://hub.docker.com/_/rabbitmq
services:
  rabbit_mq:
    image: 'rabbitmq:3.9-alpine'
    container_name: 'rabbitmq'
    ports:
      - '5671:5672'
      - '15672:15672'
    volumes:
      - /home/oem/data/rabbitmq/data/:/var/lib/rabbitmq/
      - /home/oem/data/rabbitmq/log/:/var/log/rabbitmq/
    networks:
      - rabbitmq_network
networks:
  rabbitmq_network:
    driver: bridge
