version: '3.2'
services:
  gitlab:
    image: 'gitlab/gitlab-ee:latest'
    restart: always
    # hostname: 'gitlab.example.com'
    container_name: gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        # external_url 'http://gitlab.example.com'
        # Add any other gitlab.rb configuration here, earch on its ownn line
    ports:
      - '80:80'
      - '443:443'
    volumes:
    - ~/gitlab/data:/var/opt/gitlab
    - ~/gitlab/config:/etc/gitlab
    - ~/gitlab/logs:/var/log/gitlab
