version: '3.7'
services:
  nginx:
    image: nginx:${NGINX_VERSION:-latest}
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "${NGINX_VOLUMES:-./nginx_data}:/etc/nginx/templates"
    environment:
      - NGINX_HOST=${NGINX_HOST:-foobar.com}
      - NGINX_PORT=${NGINX_PORT:-80}