version: '3.7'
services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    restart: always
    user: root
    ports:
      - 9090:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - ~/jenkins/home:/var/jenkins_home
      - ~/jenkins/run/docker.sock:/var/run/docker.sock
      - ~/jenkins/bin/docker:/usr/local/bin/docker