version: "3.7"
services:
  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      # - POSTGRES_DB=admin
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - 5432:5432
    volumes:
      - /data/db:/var/lib/postgresql/data